//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManageWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string email { get; set; }
        public string username { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
    
        public virtual UsersCredential UsersCredential { get; set; }
        public virtual OTP OTP { get; set; }
    }
}
